### ISSUE TITLE
请问楼主解决了在tensorflow上提的issue吗？

### ISSUE THREAD

**Issue by xiechengsheng** [thewintersun/distributeTensorflowExample#12]
[How to restore the model when use distributed tensorflow ??](https://github.com/tensorflow/tensorflow/issues/4436) 表示遇到了完全一模一样的问题，就是当chief worker的训练进程被重启的话就会报错，别的worker训练进程重启就没事，请问你现在解决这个问题了吗？咋解决的呀？
谢谢~

**Comment by thewintersun** [comment]
解决了
