### ISSUE TITLE
有关数据传输的问题

### ISSUE THREAD

**Issue by jinzequn** [thewintersun/distributeTensorflowExample#13]
@thewintersun 你好，我有一些问题请教：

1. 我们有5台1080的PC，搭建几台电脑之间的的分布式Tensorflow环境，电脑之间的网络传输需要在什么级别？

2. 我现在是用千兆路由器连接几台电脑，参数的传递影响很大，所以我把PS主节点和worker主节点放在同一台电脑上，这样会解决一大部分传输数据的问题，但是我发现其余的non-chief worker只发送数据而不接受数据这这样正常么？

多谢

**Comment by thewintersun** [comment]
@jinzequn 
1. 这个看你的网络的参数量，正常的话需要千兆交换机，如果模型非常大，可能需要万兆交换机。正常情况下，你如果一个机器上就一个1080的话，应该千兆足够了。
2. 这样肯定不正常。

**Comment by jinzequn** [comment]
OK，进一步问一下：

1. 我现在模型保存为ckpt大约为38M，如果将PS和worker主节点分别部署在不同电脑上，实际测在千兆路由器下（传输速率达到110MiB/s）明显的拖慢速度，训练速度甚至赶不上一台，这样的速度正常么？

2. 在ps和worker主节点在一台电脑上，其他电脑只发送数据而基本不接受数据的non-chief worker能够正常的加入训练，能获取global step，只是不获取大量的参数，发送数据为30MiB/s.但是接受数据仅为300+KiB/s，这样的情况出现过么？

3. 现在能够加速训练的网络通讯硬件应该在什么级别？我的程序能够正常的进行更新迭代，但是在千兆路由器下会严重的拖慢速度，我现在在考虑是我的程序设置网络连接有问题还是硬件带宽的限制。

**Comment by jinzequn** [comment]
问题已经解决了，多谢！
